apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  namespace: orchestr  # Assurez-vous que le namespace "orchestr" existe ou remplacez par "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: nginx-hello-world-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-hello-world-config
  namespace: orchestr
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello, World from Nginx!</h1>
        <p>This is a test page to verify the deployment.</p>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world-service
  namespace: orchestr
spec:
  selector:
    app: nginx-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

